/**
 * Generated by Showcase Visual Editor
 */

const projectData = [
    {
        "id": "ai-ops-agent",
        "title": "AI Ops Agent Studio",
        "description": "An interactive client dashboard and Agent Studio for managing AI operations, intake forms, and API services.",
        "image": "assets/project1.jpg",
        "useCustomImage": true,
        "tags": [
            "React",
            "TypeScript",
            "FastAPI",
            "Python"
        ],
        "demoLink": "https://aiopsagent.aiopsexpert.com/",
        "sourceLink": "#",
        "delayClass": ""
    },
    {
        "id": "fintech-mvp",
        "title": "FinTech Analytics MVP",
        "description": "A high-performance SaaS platform for financial data visualization, bringing real-time data streaming to retail investors.",
        "image": "assets/project2.jpg",
        "tags": [
            "Next.js",
            "Tailwind",
            "Prisma"
        ],
        "demoLink": "#",
        "sourceLink": "#",
        "delayClass": "delay-1"
    },
    {
        "id": "3d-explorer",
        "title": "3D Product Explorer",
        "description": "An interactive, cinematic product configuration experience built natively for the web, allowing deep customization at 60fps.",
        "image": "assets/project3.jpg",
        "tags": [
            "Three.js",
            "WebGL",
            "GSAP"
        ],
        "demoLink": "#",
        "sourceLink": "#",
        "delayClass": "delay-2"
    },
    {
        "id": "new-proj-1772220554727",
        "title": "AI Social Media Creator ",
        "description": "AI Social Media Creator ",
        "image": "assets/placeholder.jpg",
        "useCustomImage": false,
        "tags": [
            "React"
        ],
        "demoLink": "https://effortless-lollipop-4fd86e.netlify.app/",
        "sourceLink": "https://effortless-lollipop-4fd86e.netlify.app/",
        "delayClass": ""
    }
];